{{- define "doppler-secret" -}}
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecrets-{{ .Values.doppler.name }}
  namespace: doppler-operator-system
spec:
  tokenSecret: # Kubernetes service token secret (namespace defaults to doppler-operator-system)
    name: {{ .Values.doppler.token_secret_ref }}
  project: {{ .Values.doppler.project }}
  config: {{ .Values.doppler.config }}
  managedSecret: # Kubernetes managed secret (will be created if does not exist)
    name: {{ .Values.doppler.secret_ref }}
    namespace: {{ .Values.namespace }}
{{- end -}}
