{{- define "serviceaccount" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{ if .Values.serviceaccount.iam_role_arn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceaccount.iam_role_arn }}
    {{ end }}
{{- end -}}
